[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
argh = "0.1.9"
once_cell = "1.16.0"
paste = "1.0.9"
regex = "1.7.0"
seq-macro = "0.3.1"
